# Project information
site_name: Healthcare
# defeine TOC or order of website-
nav:
  - Home: Dataset.md
  - Data Ingestion: Data-Ingestion.md
  - Data Transformation: Data-Transformation.md
  - Model Trainer: Model-Trainer.md
  - Training Pipeline: Training-Pipeline.md
  - Prediction Pipeline: Prediction-Pipeline.md
  - Application: Application.md

site_author: Aakash Yadav
site_description: >-
  DESCRIPTION
# Repository
repo_name: Healthcare
repo_url: https://github.com/aakashsyadav1999/Healthcare.git

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aakashsyadav1999
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aakash-yadav-1897491b2/



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/aakashsyadav1999"  target="_blank" rel="noopener">Aakash Yadav</a>